name: GetScreen Windows (6H)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Downloading & Setting Up
        run: |
         echo "EMAIL_SECRET=craft12912servergga@gmail.com" > secrets.txt
         Invoke-WebRequest -Uri "https://getscreen.me/download/getscreen.exe" -OutFile "down.bat"
         cmd /c down.bat

      - name: Time Counter
        run: Start-Sleep -Seconds 21600
